import { AppTheme } from "../../theme/desingSystem";

export const createTabStyles = (theme: AppTheme) => ({
  root: {
    position: "absolute",
    left: 16,
    right: 16,
    borderRadius: 24,
    backgroundColor: "rgba(10, 10, 10, 0.85)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
    elevation: 8,
  },
  blurContainer: {
    width: "100%",
    height: 68,
    justifyContent: "center",
  },
  bar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  tabLabel: {
    color: "rgba(255, 255, 255, 0.4)",
    fontFamily: theme.typography.fontFamily.medium,
    fontSize: 9,
    marginTop: 2,
    fontWeight: "500",
  },
  tabLabelActive: {
    color: "#4ade80",
    fontWeight: "600",
  },
  centerButtonContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 6,
  },
  centerButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#4ade80",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#4ade80",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 5,
  },
  activeIndicator: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#4ade80",
    marginTop: 3,
    shadowColor: "#4ade80",
    shadowOpacity: 0.8,
    shadowRadius: 3,
    elevation: 2,
  },
} as const);
