import { AppTheme } from "../../theme/desingSystem";

export const createTabStyles = (theme: AppTheme) => ({
  root: {
    position: "absolute",
    left: 16,
    right: 16,
    borderRadius: 24,
    backgroundColor: theme.colors.tabBarBackground,
    borderWidth: 1,
    borderColor: theme.colors.tabBarBorder,
    overflow: "hidden",
    shadowColor: theme.mode === "light" ? theme.colors.textPrimary : "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: theme.mode === "light" ? 0.1 : 0.35,
    shadowRadius: theme.mode === "light" ? 10 : 15,
    elevation: theme.mode === "light" ? 5 : 8,
  },
  blurContainer: {
    width: "100%",
    height: 68,
    justifyContent: "center",
  },
  bar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  tabLabel: {
    color: theme.colors.tabBarInactive,
    fontFamily: theme.typography.fontFamily.medium,
    fontSize: 9,
    marginTop: 2,
    fontWeight: "500",
  },
  tabLabelActive: {
    color: theme.colors.tabBarActive,
    fontWeight: "600",
  },
  centerButtonContainer: {
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 6,
  },
  centerButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: theme.colors.tabBarCenterButton,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: theme.colors.tabBarCenterButton,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 5,
  },
  activeIndicator: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.colors.tabBarActive,
    marginTop: 3,
    shadowColor: theme.colors.tabBarActive,
    shadowOpacity: 0.8,
    shadowRadius: 3,
    elevation: 2,
  },
} as const);
