import { AppTheme } from "../../theme/desingSystem";

export const createTabStyles = (theme: AppTheme) => ({
    root: {
      backgroundColor: theme.colors.tabBarBackground,
      borderTopWidth: 1,
      borderTopColor: theme.colors.tabBarBorder,
      overflow: "visible",
    },
    bar: {
      flexDirection: "row",
      alignItems: "center",
      paddingTop: theme.spacing.s9,
      paddingBottom: theme.spacing.s0,
      paddingHorizontal: theme.spacing.s6,
    },
    tabItem: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: theme.spacing.s4,
    },
    tabLabel: {
      color: theme.colors.tabBarInactive,
      fontSize: theme.typography.fontSizes.xs,
      marginTop: theme.spacing.s3,
      fontWeight: theme.typography.fontWeights.medium,
    },
    tabLabelActive: {
      color: theme.colors.tabBarActive,
    },
    centerSpacer: {
      flex: 1.2,
    },
    arcWrapper: {
      position: "absolute",
      top: -theme.spacing.s29,
      left: 0,
      right: 0,
      alignItems: "center",
      zIndex: 2,
    },
    arcBump: {
      width: theme.dimensions.arcBump.width,
      height: theme.dimensions.arcBump.height,
      borderTopLeftRadius: theme.radius.full,
      borderTopRightRadius: theme.radius.full,
      backgroundColor: theme.colors.tabBarBackground,
      borderTopWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderBottomWidth: 0,
      borderColor: theme.colors.tabBarBorder,
    },
    centerButtonWrapper: {
      position: "absolute",
      top: -theme.spacing.s22,
      left: 0,
      right: 0,
      alignItems: "center",
      zIndex: 10,
    },
    centerButton: {
      width: theme.dimensions.centerButton.width,
      height: theme.dimensions.centerButton.height,
      borderRadius: theme.radius.centerButton,
      backgroundColor: theme.colors.tabBarCenterButton,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 0,
      shadowColor: theme.shadows.centerButton.color,
      shadowOpacity: theme.shadows.centerButton.opacity,
      shadowRadius: theme.shadows.centerButton.radius,
      shadowOffset: theme.shadows.centerButton.offset,
      elevation: theme.shadows.centerButton.elevation,
  },
} as const);
