import { AppTheme } from "../../theme/desingSystem";

export const createMisPlantasStyles = (theme: AppTheme) => ({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  bgImage: {
    opacity: theme.opacity.backgroundTexture,
    tintColor: theme.colors.primary,
  },
  header: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.s18,
    paddingVertical: theme.spacing.s8,
    marginHorizontal: theme.spacing.s16,
    marginTop: theme.spacing.s6,
    marginBottom: theme.spacing.s4,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    shadowColor: theme.shadows.card.color,
    shadowOpacity: theme.shadows.card.opacity,
    shadowRadius: theme.shadows.card.radius,
    shadowOffset: theme.shadows.card.offset,
    elevation: theme.shadows.card.elevation,
  },
  headerTitle: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["5xl"],
    fontWeight: theme.typography.fontWeights.bold,
    letterSpacing: theme.typography.letterSpacing.md,
  },
  filterBtn: {
    width: theme.dimensions.settingsButton.width,
    height: theme.dimensions.settingsButton.height,
    borderRadius: theme.radius.sm,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: theme.spacing.s16,
    paddingTop: theme.spacing.s12,
    paddingBottom: theme.spacing.s20,
  },
  summaryCard: {
    flexDirection: "row" as const,
    gap: theme.spacing.s10,
    marginBottom: theme.spacing.s14,
  },
  summaryItem: {
    flex: 1,
    alignItems: "center" as const,
    backgroundColor: theme.colors.accentDim,
    borderRadius: theme.radius.lg,
    paddingVertical: theme.spacing.s12,
    paddingHorizontal: theme.spacing.s8,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.accentWithAlpha,
    gap: theme.spacing.s2,
  },
  summaryValue: {
    color: theme.colors.primary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["5xl"],
    fontWeight: theme.typography.fontWeights.bold,
  },
  summaryLabel: {
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.base,
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["2xl"],
    fontWeight: theme.typography.fontWeights.bold,
    letterSpacing: theme.typography.letterSpacing.sm,
  },
  sectionRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginBottom: theme.spacing.s14,
  },
  sectionAccentBar: {
    width: 3,
    height: 18,
    borderRadius: 2,
    backgroundColor: theme.colors.primary,
    marginRight: theme.spacing.s8,
  },
  grid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: theme.spacing.s12,
    marginBottom: theme.spacing.s14,
  },
  plantCard: {
    width: "47%" as const,
    aspectRatio: 0.72,
    borderRadius: theme.radius.xl,
    overflow: "hidden" as const,
    backgroundColor: theme.colors.surface,
    shadowColor: theme.shadows.card.color,
    shadowOpacity: theme.shadows.card.opacity,
    shadowRadius: theme.shadows.card.radius,
    shadowOffset: theme.shadows.card.offset,
    elevation: theme.shadows.card.elevation,
  },
  plantImage: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%" as const,
    height: "100%" as const,
  },
  plantChip: {
    paddingHorizontal: theme.spacing.s8,
    paddingVertical: theme.spacing.s2,
    backgroundColor: "rgba(13,17,23,0.82)" as const,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.accentWithAlpha,
  },
  plantChipText: {
    color: theme.colors.primary,
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semibold,
  },
  plantCardOverlay: {
    paddingHorizontal: theme.spacing.s12,
    paddingBottom: theme.spacing.s12,
    paddingTop: theme.spacing.s22,
    backgroundColor: "rgba(0,0,0,0.6)" as const,
  },
  plantName: {
    color: theme.colors.textOnAccent,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["2xl"],
    fontWeight: theme.typography.fontWeights.bold,
    marginBottom: theme.spacing.s4,
  },
  waterRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: theme.spacing.s4,
  },
  waterText: {
    color: theme.colors.primary,
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semibold,
  },

  // ── Pending sync ─────────────────────────────────────────────────────────────
  pendingBadge: {
    position: "absolute" as const,
    top: theme.spacing.s8,
    right: theme.spacing.s8,
    backgroundColor: "rgba(0,0,0,0.6)" as const,
    paddingHorizontal: theme.spacing.s8,
    paddingVertical: theme.spacing.s4,
    borderRadius: theme.radius.full,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: theme.spacing.s4,
    borderWidth: theme.borders.thin,
    borderColor: "rgba(255,255,255,0.2)" as const,
  },
  pendingText: {
    color: theme.colors.textOnAccent,
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: 10,
    fontWeight: theme.typography.fontWeights.semibold,
    textTransform: "uppercase" as const,
  },

  // ── Health & alert ──────────────────────────────────────────────────────────────────
  healthDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  alertBanner: {
    backgroundColor: theme.colors.warningDim,
    borderRadius: theme.radius.lg,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.warningWithAlpha,
    padding: theme.spacing.s14,
    marginBottom: theme.spacing.s14,
    gap: theme.spacing.s8,
  },
  alertHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: theme.spacing.s6,
    marginBottom: theme.spacing.s2,
  },
  alertTitle: {
    color: theme.colors.warning,
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes.md,
    fontWeight: theme.typography.fontWeights.semibold,
  },
  alertItem: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: theme.spacing.s8,
  },
  alertPlantName: {
    flex: 1,
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.md,
  },
  alertWaterText: {
    color: theme.colors.warning,
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semibold,
  },

  // ── FAB ─────────────────────────────────────────────────────────────────────
  fab: {
    position: "absolute" as const,
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.colors.primary,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.5,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
  },

  // ── Modal ────────────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: "flex-end" as const,
  },
  modalCard: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: theme.spacing.s20,
    paddingBottom: theme.spacing.s20,
    paddingTop: theme.spacing.s12,
    gap: theme.spacing.s18,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.colors.border,
    alignSelf: "center" as const,
    marginBottom: theme.spacing.s4,
  },
  modalHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
  },
  modalTitle: {
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["5xl"],
    fontWeight: theme.typography.fontWeights.bold,
    color: theme.colors.textPrimary,
    letterSpacing: theme.typography.letterSpacing.sm,
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.backgroundChip,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },

  // ── Inputs dentro del modal ──────────────────────────────────────────────────
  fieldLabel: {
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes["2xl"],
    fontWeight: theme.typography.fontWeights.semibold,
    color: theme.colors.textPrimary,
    marginBottom: theme.scale.sm,
  },
  textInput: {
    height: theme.dimensions.inputHeight,
    borderRadius: theme.radius.md,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.backgroundChip,
    paddingHorizontal: theme.spacing.s16,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes["2xl"],
    color: theme.colors.textPrimary,
  },
  textInputError: {
    borderColor: theme.colors.error,
  },
  fieldError: {
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.base,
    color: theme.colors.error,
    marginTop: theme.scale.xs,
  },

  // ── Chips de categoría ───────────────────────────────────────────────────────
  chipsRow: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: theme.scale.sm,
  },
  chip: {
    paddingHorizontal: theme.spacing.s12,
    paddingVertical: theme.spacing.s6,
    borderRadius: theme.radius.pill,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.backgroundChip,
  },
  chipSelected: {
    backgroundColor: theme.colors.accentDim,
    borderColor: theme.colors.primary,
  },
  chipText: {
    fontFamily: theme.typography.fontFamily.medium,
    fontSize: theme.typography.fontSizes.md,
    fontWeight: theme.typography.fontWeights.medium,
    color: theme.colors.textSecondary,
  },
  chipTextSelected: {
    color: theme.colors.primary,
  },

  // ── Botón guardar ────────────────────────────────────────────────────────────
  saveButton: {
    height: theme.dimensions.inputHeight,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.primary,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 6,
  },
  saveButtonText: {
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes["2xl"],
    fontWeight: theme.typography.fontWeights.semibold,
    color: theme.colors.textOnAccent,
    letterSpacing: theme.typography.letterSpacing.md,
  },
  // ── Search Bar ──────────────────────────────────────────────────────────────
  searchBar: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    paddingHorizontal: theme.spacing.s14,
    height: 46,
    marginHorizontal: theme.spacing.s16,
    marginTop: theme.spacing.s10,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    gap: theme.spacing.s10,
  },
  searchInput: {
    flex: 1,
    fontSize: theme.typography.fontSizes.md,
    color: theme.colors.textPrimary,
    padding: 0,
  },
  // ── Empty State ─────────────────────────────────────────────────────────────
  emptyContainer: {
    flex: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingVertical: theme.spacing.s44,
    width: "100%" as const,
    gap: theme.spacing.s12,
  },
  emptyText: {
    fontFamily: theme.typography.fontFamily.medium,
    fontSize: theme.typography.fontSizes.md,
    textAlign: "center" as const,
  },
});
