import { AppTheme } from "../../theme/desingSystem";

export const createMisPlantasStyles = (theme: AppTheme) => ({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  bgImage: {
    opacity: theme.opacity.backgroundTexture,
    tintColor: theme.colors.primary,
  },
  header: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.s18,
    paddingVertical: theme.spacing.s8,
    marginHorizontal: theme.spacing.s16,
    marginTop: theme.spacing.s6,
    marginBottom: theme.spacing.s4,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    shadowColor: theme.shadows.card.color,
    shadowOpacity: theme.shadows.card.opacity,
    shadowRadius: theme.shadows.card.radius,
    shadowOffset: theme.shadows.card.offset,
    elevation: theme.shadows.card.elevation,
  },
  headerTitle: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["5xl"],
    fontWeight: theme.typography.fontWeights.bold,
    letterSpacing: theme.typography.letterSpacing.md,
  },
  filterBtn: {
    width: theme.dimensions.settingsButton.width,
    height: theme.dimensions.settingsButton.height,
    borderRadius: theme.radius.sm,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: theme.spacing.s16,
    paddingTop: theme.spacing.s12,
    paddingBottom: theme.spacing.s20,
  },
  summaryCard: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: theme.spacing.s18,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    shadowColor: theme.shadows.card.color,
    shadowOpacity: theme.shadows.card.opacity,
    shadowRadius: theme.shadows.card.radius,
    shadowOffset: theme.shadows.card.offset,
    elevation: theme.shadows.card.elevation,
    marginBottom: theme.spacing.s14,
    flexDirection: "row" as const,
    justifyContent: "space-around" as const,
    alignItems: "center" as const,
  },
  summaryItem: {
    alignItems: "center" as const,
  },
  summaryValue: {
    color: theme.colors.primary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["4xl"],
    fontWeight: theme.typography.fontWeights.bold,
  },
  summaryLabel: {
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.base,
    marginTop: theme.spacing.s3,
  },
  summaryDivider: {
    width: theme.borders.thin,
    height: theme.spacing.s44,
    backgroundColor: theme.colors.border,
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["2xl"],
    fontWeight: theme.typography.fontWeights.bold,
    marginBottom: theme.spacing.s14,
    letterSpacing: theme.typography.letterSpacing.sm,
  },
  grid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: theme.spacing.s10,
    marginBottom: theme.spacing.s14,
  },
  plantCard: {
    width: "47.5%" as const,
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.lg,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    overflow: "hidden" as const,
    shadowColor: theme.shadows.card.color,
    shadowOpacity: theme.shadows.card.opacity,
    shadowRadius: theme.shadows.card.radius,
    shadowOffset: theme.shadows.card.offset,
    elevation: theme.shadows.card.elevation,
  },
  plantImage: {
    width: "100%" as const,
    height: theme.dimensions.categoryCard.height,
  },
  plantCardBody: {
    padding: theme.spacing.s12,
  },
  plantName: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes.md,
    fontWeight: theme.typography.fontWeights.semibold,
    marginBottom: theme.spacing.s4,
    lineHeight: theme.typography.lineHeights.normal,
  },
  categoryChip: {
    alignSelf: "flex-start" as const,
    paddingHorizontal: theme.spacing.s8,
    paddingVertical: theme.spacing.s3,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.accentDim,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.accentWithAlpha,
    marginBottom: theme.spacing.s6,
  },
  categoryChipText: {
    color: theme.colors.primary,
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes.xs,
    fontWeight: theme.typography.fontWeights.semibold,
  },
  waterRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: theme.spacing.s4,
    marginTop: theme.spacing.s4,
  },
  waterText: {
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.xs,
  },
});
