import { AppTheme } from "../../theme/desingSystem";

export const createMisPlantasStyles = (theme: AppTheme) => ({
  safeArea: {
    flex: 1,
    backgroundColor: "#0A0A0A",
  },
  container: {
    flex: 1,
    backgroundColor: "#0A0A0A",
  },
  bgImage: {
    opacity: 0.04,
    tintColor: "#4ade80",
  },
  header: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  headerTitle: {
    color: "#FFFFFF",
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: 22,
    fontWeight: "300" as const,
    letterSpacing: -0.5,
  },
  filterBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
  },
  searchBar: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 46,
    marginHorizontal: 16,
    marginTop: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    color: "#FFFFFF",
    padding: 0,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 0,
    paddingTop: 0,
    paddingBottom: 130, // Account for the floating tab bar height at the bottom
  },
  summaryCard: {
    flexDirection: "row" as const,
    gap: 10,
    marginBottom: 20,
  },
  summaryItem: {
    flex: 1,
    alignItems: "center" as const,
    backgroundColor: "rgba(74, 222, 128, 0.04)",
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 128, 0.15)",
    gap: 2,
  },
  summaryValue: {
    color: "#4ade80",
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: 22,
    fontWeight: "700" as const,
  },
  summaryLabel: {
    color: "rgba(255, 255, 255, 0.4)",
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: 11,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: 16,
    fontWeight: "600" as const,
    letterSpacing: 0.2,
  },
  sectionRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginBottom: 14,
    marginTop: 10,
  },
  sectionAccentBar: {
    width: 3,
    height: 16,
    borderRadius: 2,
    backgroundColor: "#4ade80",
    marginRight: 8,
  },
  grid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 12,
    marginBottom: 14,
  },
  plantCard: {
    width: "48%" as const,
    aspectRatio: 0.72,
    borderRadius: 24,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    padding: 8,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  imageContainer: {
    width: "100%" as const,
    height: "65%" as const,
    borderRadius: 18,
    overflow: "hidden" as const,
    position: "relative" as const,
  },
  plantImage: {
    width: "100%" as const,
    height: "100%" as const,
  },
  plantChip: {
    position: "absolute" as const,
    top: 6,
    left: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(74, 222, 128, 0.2)",
    flexDirection: "row" as const,
    alignItems: "center" as const,
  },
  plantChipText: {
    color: "#4ade80",
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: 9,
    fontWeight: "600" as const,
    letterSpacing: 0.2,
  },
  plantInfoContainer: {
    paddingHorizontal: 4,
    paddingVertical: 8,
    flex: 1,
    justifyContent: "center" as const,
  },
  plantName: {
    color: "#FFFFFF",
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: 14,
    fontWeight: "700" as const,
    marginBottom: 4,
  },
  waterRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 6,
  },
  waterText: {
    color: "#4ade80",
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: 11,
    fontWeight: "600" as const,
  },

  // ── Pending sync ─────────────────────────────────────────────────────────────
  pendingBadge: {
    position: "absolute" as const,
    top: 6,
    right: 6,
    backgroundColor: "rgba(0, 0, 0, 0.65)" as const,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 4,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)" as const,
  },
  pendingText: {
    color: "#FFFFFF",
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: 9,
    fontWeight: "600" as const,
    textTransform: "uppercase" as const,
  },

  // ── Health & alert ──────────────────────────────────────────────────────────────────
  healthDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  alertBanner: {
    backgroundColor: "rgba(245, 158, 11, 0.04)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(245, 158, 11, 0.18)",
    padding: 14,
    marginBottom: 14,
    gap: 8,
  },
  alertHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 6,
    marginBottom: 2,
  },
  alertTitle: {
    color: "#F59E0B",
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: 13,
    fontWeight: "600" as const,
  },
  alertItem: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  alertPlantName: {
    flex: 1,
    color: "rgba(255, 255, 255, 0.8)",
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: 13,
  },
  alertWaterText: {
    color: "#F59E0B",
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: 11,
    fontWeight: "600" as const,
  },

  // ── FAB ─────────────────────────────────────────────────────────────────────
  fab: {
    position: "absolute" as const,
    bottom: 120, // Floats cleanly right above the floating glassy tab bar on all devices
    right: 20,
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#4ade80",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    shadowColor: "#4ade80",
    shadowOpacity: 0.35,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },

  // ── Modal ────────────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    justifyContent: "flex-end" as const,
  },
  modalCard: {
    backgroundColor: "#121212",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
    paddingHorizontal: 20,
    paddingBottom: 30,
    paddingTop: 12,
    gap: 16,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    alignSelf: "center" as const,
    marginBottom: 4,
  },
  modalHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
  },
  modalTitle: {
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: 18,
    fontWeight: "700" as const,
    color: "#FFFFFF",
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },

  // ── Inputs dentro del modal ──────────────────────────────────────────────────
  fieldLabel: {
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: 13,
    fontWeight: "600" as const,
    color: "rgba(255, 255, 255, 0.7)",
    marginBottom: 6,
  },
  textInput: {
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.04)",
    paddingHorizontal: 16,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: 13,
    color: "#FFFFFF",
  },
  textInputError: {
    borderColor: "#F87171",
  },
  fieldError: {
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: 11,
    color: "#F87171",
    marginTop: 4,
  },

  // ── Chips de categoría ───────────────────────────────────────────────────────
  chipsRow: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.06)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
  },
  chipSelected: {
    backgroundColor: "rgba(74, 222, 128, 0.08)",
    borderColor: "#4ade80",
  },
  chipText: {
    fontFamily: theme.typography.fontFamily.medium,
    fontSize: 12,
    fontWeight: "500" as const,
    color: "rgba(255, 255, 255, 0.4)",
  },
  chipTextSelected: {
    color: "#4ade80",
  },

  // ── Botón guardar ────────────────────────────────────────────────────────────
  saveButton: {
    height: 48,
    borderRadius: 14,
    backgroundColor: "#4ade80",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    marginTop: 10,
  },
  saveButtonText: {
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: 14,
    fontWeight: "700" as const,
    color: "#000000",
  },
  // ── Empty State ─────────────────────────────────────────────────────────────
  emptyContainer: {
    flex: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingVertical: 60,
    width: "100%" as const,
    gap: 12,
  },
  emptyText: {
    fontFamily: theme.typography.fontFamily.medium,
    fontSize: 13,
    textAlign: "center" as const,
  },
});
