import { StyleSheet } from "react-native";

const colors = {
  background: "#0D1117",
  card: "#161B22",
  border: "#21262D",
  accent: "#34D399",
  accentDim: "#163330",
  textPrimary: "#E6EDF3",
  textSecondary: "#8B949E",
  chip: "#1C2128",
};

export { colors };

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  bgImage: {
    opacity: 0.07,
    tintColor: "#34D399",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.background,
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    marginBottom: 14,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarWrapper: {
    borderRadius: 46,
    borderWidth: 2.5,
    borderColor: colors.accent,
    marginRight: 16,
    padding: 3,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  nameBlock: {
    flex: 1,
  },
  nameText: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 26,
  },
  handleText: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
  },
  privacyPill: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: colors.accentDim,
    borderWidth: 1,
    borderColor: colors.accent + "60",
  },
  privacyText: {
    color: colors.accent,
    fontWeight: "700",
    fontSize: 12,
    letterSpacing: 0.4,
  },
  description: {
    marginTop: 14,
    color: colors.textSecondary,
    lineHeight: 21,
    fontSize: 14,
  },
  metricsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  metricCard: {
    flex: 1,
    backgroundColor: colors.chip,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 10,
    alignItems: "flex-start",
    overflow: "hidden",
  },
  metricCardLast: {
    marginRight: 0,
  },
  metricGrassImage: {
    position: "absolute",
    bottom: -6,
    right: -8,
    width: 58,
    height: 58,
    opacity: 0.35,
  },
  metricIcon: {
    fontSize: 20,
    marginBottom: 4,
  },
  metricLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    textAlign: "left",
  },
  metricValue: {
    color: colors.accent,
    fontSize: 17,
    fontWeight: "700",
    marginTop: 3,
    textAlign: "left",
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 14,
    letterSpacing: 0.2,
  },
  favoriteImageFull: {
    width: "100%",
    height: 170,
    borderRadius: 14,
    backgroundColor: colors.chip,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
  },
  favoriteSubLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    marginBottom: 3,
    letterSpacing: 0.2,
  },
  favoriteName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "700",
    fontStyle: "italic",
  },
  chipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.chip,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },

  // ── Profile card redesign ──────────────────────────────
  bannerContainer: {
    height: 130,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: "hidden",
  },
  bannerImage: {
    width: "100%",
    height: "100%",
  },
  avatarOuter: {
    alignItems: "center",
    marginTop: -44,
  },
  profileInfoCenter: {
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  nameCentered: {
    color: colors.textPrimary,
    fontSize: 22,
    fontWeight: "700",
    textAlign: "center",
    letterSpacing: 0.2,
  },
  handleCentered: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 3,
    textAlign: "center",
  },
  privacyPillCenter: {
    alignSelf: "center",
    marginTop: 8,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: colors.accentDim,
    borderWidth: 1,
    borderColor: colors.accent + "60",
  },
  descriptionCentered: {
    marginTop: 10,
    color: colors.textSecondary,
    lineHeight: 20,
    fontSize: 13,
    textAlign: "center",
  },
  profileDivider: {
    height: 1,
    backgroundColor: colors.border,
    marginHorizontal: 16,
    marginTop: 14,
  },
  profileActionRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 16,
    alignItems: "center",
  },
  editBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    backgroundColor: colors.chip,
  },
  editBtnText: {
    color: colors.textPrimary,
    fontWeight: "600",
    fontSize: 13,
  },
  shareBtn: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Category grid cards ────────────────────────────────
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  categoryCardItem: {
    width: "47%",
    height: 90,
    backgroundColor: colors.chip,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 14,
    overflow: "hidden",
    justifyContent: "flex-start",
  },
  categoryCardItemFull: {
    width: "100%",
  },
  categoryCardTitle: {
    color: colors.textPrimary,
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.1,
  },
  categoryCardSub: {
    color: colors.textSecondary,
    fontSize: 11,
    marginTop: 4,
    lineHeight: 15,
  },
  categoryCardIcon: {
    position: "absolute",
    bottom: -8,
    right: -4,
    opacity: 0.15,
  },
});
