import { StyleSheet } from "react-native";

const colors = {
  background: "#0D1117",
  card: "#161B22",
  border: "#21262D",
  accent: "#34D399",
  accentDim: "#163330",
  textPrimary: "#E6EDF3",
  textSecondary: "#8B949E",
  chip: "#1C2128",
};

export { colors };

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  bgImage: {
    opacity: 0.07,
    tintColor: "#34D399",
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 20,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.background,
  },
  headerTitle: {
    color: colors.textPrimary,
    fontSize: 24,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    marginBottom: 14,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarWrapper: {
    borderRadius: 46,
    borderWidth: 2.5,
    borderColor: colors.accent,
    marginRight: 16,
    padding: 3,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  nameBlock: {
    flex: 1,
  },
  nameText: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: "700",
    lineHeight: 26,
  },
  handleText: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 2,
  },
  privacyPill: {
    alignSelf: "flex-start",
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: colors.accentDim,
    borderWidth: 1,
    borderColor: colors.accent + "60",
  },
  privacyText: {
    color: colors.accent,
    fontWeight: "700",
    fontSize: 12,
    letterSpacing: 0.4,
  },
  description: {
    marginTop: 14,
    color: colors.textSecondary,
    lineHeight: 21,
    fontSize: 14,
  },
  metricsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  metricCard: {
    flex: 1,
    backgroundColor: colors.chip,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: colors.border,
    marginRight: 10,
    alignItems: "center",
  },
  metricCardLast: {
    marginRight: 0,
  },
  metricIcon: {
    fontSize: 20,
    marginBottom: 4,
  },
  metricLabel: {
    color: colors.textSecondary,
    fontSize: 11,
    textAlign: "center",
  },
  metricValue: {
    color: colors.accent,
    fontSize: 17,
    fontWeight: "700",
    marginTop: 3,
    textAlign: "center",
  },
  sectionTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 14,
    letterSpacing: 0.2,
  },
  favoriteImageFull: {
    width: "100%",
    height: 170,
    borderRadius: 14,
    backgroundColor: colors.chip,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 12,
  },
  favoriteSubLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    marginBottom: 3,
    letterSpacing: 0.2,
  },
  favoriteName: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: "700",
    fontStyle: "italic",
  },
  chipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.chip,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: "600",
  },
});
