import { AppTheme } from "../../theme/desingSystem";

export const createStyles = (theme: AppTheme) => ({
  safeArea: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  bgImage: {
    opacity: theme.opacity.backgroundTexture,
    tintColor: theme.colors.primary,
  },
  scrollContent: {
    paddingHorizontal: theme.spacing.s16,
    paddingTop: theme.spacing.s12,
    paddingBottom: theme.spacing.s20,
  },
  scrollView: {
    flex: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.full,
    paddingHorizontal: theme.spacing.s18,
    paddingVertical: theme.spacing.s8,
    marginHorizontal: theme.spacing.s16,
    marginTop: theme.spacing.s6,
    marginBottom: theme.spacing.s4,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    shadowColor: theme.shadows.card.color,
    shadowOpacity: theme.shadows.card.opacity,
    shadowRadius: theme.shadows.card.radius,
    shadowOffset: theme.shadows.card.offset,
    elevation: theme.shadows.card.elevation,
  },
  headerTitle: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["5xl"],
    fontWeight: theme.typography.fontWeights.bold,
    letterSpacing: theme.typography.letterSpacing.md,
  },
  settingsBtn: {
    width: theme.dimensions.settingsButton.width,
    height: theme.dimensions.settingsButton.height,
    borderRadius: theme.radius.sm,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.surfaceElevated,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
  },
  card: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: theme.spacing.s18,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    shadowColor: theme.shadows.card.color,
    shadowOpacity: theme.shadows.card.opacity,
    shadowRadius: theme.shadows.card.radius,
    shadowOffset: theme.shadows.card.offset,
    elevation: theme.shadows.card.elevation,
    marginBottom: theme.spacing.s14,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarWrapper: {
    borderRadius: theme.radius.avatar,
    borderWidth: theme.borders.avatarRing,
    borderColor: theme.colors.primary,
    marginRight: theme.spacing.s16,
    padding: theme.spacing.s3,
  },
  avatar: {
    width: theme.dimensions.avatar.width,
    height: theme.dimensions.avatar.height,
    borderRadius: theme.radius.avatarInner,
  },
  nameBlock: {
    flex: 1,
  },
  nameText: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["5xl"],
    fontWeight: theme.typography.fontWeights.bold,
    lineHeight: theme.typography.lineHeights.loose,
  },
  handleText: {
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.md,
    marginTop: theme.spacing.s2,
  },
  privacyPill: {
    alignSelf: "flex-start",
    marginTop: theme.spacing.s10,
    paddingHorizontal: theme.spacing.s12,
    paddingVertical: theme.spacing.s4,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.accentDim,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.accentWithAlpha,
  },
  privacyText: {
    color: theme.colors.primary,
    fontFamily: theme.typography.fontFamily.bold,
    fontWeight: theme.typography.fontWeights.bold,
    fontSize: theme.typography.fontSizes.base,
    letterSpacing: theme.typography.letterSpacing.lg,
  },
  description: {
    marginTop: theme.spacing.s14,
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    lineHeight: theme.typography.lineHeights.relaxed,
    fontSize: theme.typography.fontSizes.lg,
  },
  metricsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  metricCard: {
    flex: 1,
    backgroundColor: theme.colors.backgroundChip,
    borderRadius: theme.radius.md,
    paddingVertical: theme.spacing.s12,
    paddingHorizontal: theme.spacing.s10,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    borderLeftWidth: 3,
    borderLeftColor: theme.colors.primary,
    marginRight: theme.spacing.s10,
    alignItems: "flex-start",
    overflow: "hidden",
  },
  metricCardLast: {
    marginRight: theme.spacing.s0,
  },
  metricGrassImage: {
    position: "absolute",
    bottom: -theme.spacing.s6,
    right: -theme.spacing.s8,
    width: theme.dimensions.metricDecorImage.width,
    height: theme.dimensions.metricDecorImage.height,
    opacity: theme.opacity.decorativeImage,
  },
  metricIcon: {
    fontSize: theme.typography.fontSizes["5xl"],
    marginBottom: theme.spacing.s4,
  },
  metricLabel: {
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.sm,
    textAlign: "left",
  },
  metricValue: {
    color: theme.colors.primary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["4xl"],
    fontWeight: theme.typography.fontWeights.bold,
    marginTop: theme.spacing.s3,
    textAlign: "left",
  },
  sectionTitle: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["2xl"],
    fontWeight: theme.typography.fontWeights.bold,
    letterSpacing: theme.typography.letterSpacing.sm,
  },
  favoriteImageWrapper: {
    width: "100%" as const,
    height: 200,
    borderRadius: theme.radius.md,
    overflow: "hidden" as const,
    marginBottom: theme.spacing.s12,
    backgroundColor: theme.colors.backgroundChip,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
  },
  favoriteImageFull: {
    width: "100%" as const,
    height: "100%" as const,
  },
  favoriteOverlay: {
    position: "absolute" as const,
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: theme.spacing.s14,
    paddingBottom: theme.spacing.s12,
    paddingTop: theme.spacing.s20,
    backgroundColor: "rgba(0,0,0,0.55)" as const,
  },
  favoriteNameOnImage: {
    color: theme.colors.textOnAccent,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["4xl"],
    fontWeight: theme.typography.fontWeights.bold,
    fontStyle: "italic" as const,
  },
  favoriteSubOnImage: {
    color: "rgba(255,255,255,0.7)" as const,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.base,
    marginBottom: theme.spacing.s2,
  },
  favoriteSubLabel: {
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.base,
    marginBottom: theme.spacing.s3,
    letterSpacing: theme.typography.letterSpacing.sm,
  },
  favoriteName: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["4xl"],
    fontWeight: theme.typography.fontWeights.bold,
    fontStyle: "italic",
  },
  chipsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.s8,
  },
  chip: {
    paddingHorizontal: theme.spacing.s14,
    paddingVertical: theme.spacing.s8,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.backgroundChip,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
  },
  chipText: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes.md,
    fontWeight: theme.typography.fontWeights.semibold,
  },

  // ── Profile card redesign ──────────────────────────────
  bannerContainer: {
    height: theme.dimensions.bannerHeight,
    borderTopLeftRadius: theme.radius.xl,
    borderTopRightRadius: theme.radius.xl,
    overflow: "hidden",
  },
  bannerImage: {
    width: "100%",
    height: "100%",
  },
  avatarOuter: {
    alignItems: "center",
    marginTop: -theme.spacing.s44,
  },
  profileInfoCenter: {
    alignItems: "center",
    paddingHorizontal: theme.spacing.s20,
    paddingTop: theme.spacing.s8,
  },
  nameCentered: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["6xl"],
    fontWeight: theme.typography.fontWeights.bold,
    textAlign: "center",
    letterSpacing: theme.typography.letterSpacing.sm,
  },
  handleCentered: {
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.md,
    marginTop: theme.spacing.s3,
    textAlign: "center",
  },
  privacyPillCenter: {
    alignSelf: "center",
    marginTop: theme.spacing.s8,
    paddingHorizontal: theme.spacing.s12,
    paddingVertical: theme.spacing.s4,
    borderRadius: theme.radius.pill,
    backgroundColor: theme.colors.accentDim,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.accentWithAlpha,
  },
  descriptionCentered: {
    marginTop: theme.spacing.s10,
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    lineHeight: theme.typography.lineHeights.normal,
    fontSize: theme.typography.fontSizes.md,
    textAlign: "center",
  },
  profileDivider: {
    height: theme.borders.thin,
    backgroundColor: theme.colors.border,
    marginHorizontal: theme.spacing.s16,
    marginTop: theme.spacing.s14,
  },
  profileActionRow: {
    flexDirection: "row",
    gap: theme.spacing.s10,
    paddingHorizontal: theme.spacing.s16,
    paddingTop: theme.spacing.s12,
    paddingBottom: theme.spacing.s16,
    alignItems: "center",
  },
  editBtn: {
    flex: 1,
    paddingVertical: theme.spacing.s10,
    borderRadius: theme.radius.md,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.accentWithAlpha,
    alignItems: "center",
    backgroundColor: theme.colors.accentDim,
  },
  editBtnText: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.semibold,
    fontWeight: theme.typography.fontWeights.semibold,
    fontSize: theme.typography.fontSizes.md,
  },
  shareBtn: {
    width: theme.dimensions.shareButton.width,
    height: theme.dimensions.shareButton.height,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Category grid cards ────────────────────────────────
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: theme.spacing.s10,
  },
  categoryCardItem: {
    width: theme.dimensions.categoryCard.width,
    height: theme.dimensions.categoryCard.height,
    backgroundColor: theme.colors.accentDim,
    borderRadius: theme.radius.lg,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.accentWithAlpha,
    padding: theme.spacing.s14,
    overflow: "hidden",
    justifyContent: "flex-start",
  },
  categoryCardItemFull: {
    width: "100%",
  },
  categoryCardTitle: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes.xl,
    fontWeight: theme.typography.fontWeights.bold,
    letterSpacing: theme.typography.letterSpacing.xs,
  },
  categoryCardSub: {
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.sm,
    marginTop: theme.spacing.s4,
    lineHeight: theme.typography.lineHeights.tight,
  },
  categoryCardIcon: {
    position: "absolute",
    bottom: -theme.spacing.s8,
    right: -theme.spacing.s4,
    opacity: theme.opacity.categoryCardIcon,
  },
  // ── Card layout variants ───────────────────────────────
  cardNoPadding: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    padding: theme.spacing.s0,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    shadowColor: theme.shadows.card.color,
    shadowOpacity: theme.shadows.card.opacity,
    shadowRadius: theme.shadows.card.radius,
    shadowOffset: theme.shadows.card.offset,
    elevation: theme.shadows.card.elevation,
    marginBottom: theme.spacing.s14,
  },
  cardMetrics: {
    backgroundColor: theme.colors.surface,
    borderRadius: theme.radius.xl,
    paddingVertical: theme.spacing.s16,
    paddingHorizontal: theme.spacing.s18,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    shadowColor: theme.shadows.card.color,
    shadowOpacity: theme.shadows.card.opacity,
    shadowRadius: theme.shadows.card.radius,
    shadowOffset: theme.shadows.card.offset,
    elevation: theme.shadows.card.elevation,
    marginBottom: theme.spacing.s14,
  },
  avatarWrapperCenter: {
    borderRadius: theme.radius.avatar,
    borderWidth: theme.borders.avatarRing,
    borderColor: theme.colors.primary,
    marginRight: theme.spacing.s0,
    padding: theme.spacing.s3,
  },
  bannerOverlay: {
    position: "absolute" as const,
    bottom: 0,
    left: 0,
    right: 0,
    height: 60,
    backgroundColor: "rgba(0,0,0,0.4)" as const,
  },
  sectionRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    marginBottom: theme.spacing.s14,
  },
  sectionAccentBar: {
    width: 3,
    height: 18,
    borderRadius: 2,
    backgroundColor: theme.colors.primary,
    marginRight: theme.spacing.s8,
  },

  // ── Logros / badges ───────────────────────────────────
  badgesRow: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: theme.spacing.s10,
  },
  badgeItem: {
    width: "47%" as const,
    backgroundColor: theme.colors.backgroundChip,
    borderRadius: theme.radius.md,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    padding: theme.spacing.s14,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: theme.spacing.s12,
  },
  badgeItemLocked: {
    opacity: 0.4,
  },
  badgeIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.colors.accentDim,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.accentWithAlpha,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  badgeIconWrapLocked: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
  },
  badgeTexts: {
    flex: 1,
  },
  badgeName: {
    color: theme.colors.textPrimary,
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes.md,
    fontWeight: theme.typography.fontWeights.semibold,
  },
  badgeNameLocked: {
    color: theme.colors.textSecondary,
  },
  badgeSub: {
    color: theme.colors.textSecondary,
    fontFamily: theme.typography.fontFamily.regular,
    fontSize: theme.typography.fontSizes.xs,
    marginTop: 2,
  },

  // ── Modal editar perfil ───────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: "flex-end" as const,
  },
  modalCard: {
    backgroundColor: theme.colors.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: theme.spacing.s20,
    paddingBottom: theme.spacing.s20,
    paddingTop: theme.spacing.s12,
    gap: theme.spacing.s18,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.colors.border,
    alignSelf: "center" as const,
    marginBottom: theme.spacing.s4,
  },
  modalHeader: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
  },
  modalTitle: {
    fontFamily: theme.typography.fontFamily.bold,
    fontSize: theme.typography.fontSizes["5xl"],
    fontWeight: theme.typography.fontWeights.bold,
    color: theme.colors.textPrimary,
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: theme.radius.sm,
    backgroundColor: theme.colors.backgroundChip,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  fieldLabel: {
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes["2xl"],
    fontWeight: theme.typography.fontWeights.semibold,
    color: theme.colors.textPrimary,
    marginBottom: theme.scale.sm,
  },
  chipsRow: {
    flexDirection: "row" as const,
    gap: theme.scale.sm,
  },
  modalChip: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: theme.scale.xs,
    paddingHorizontal: theme.spacing.s12,
    paddingVertical: theme.spacing.s8,
    borderRadius: theme.radius.pill,
    borderWidth: theme.borders.thin,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.backgroundChip,
  },
  modalChipSelected: {
    backgroundColor: theme.colors.accentDim,
    borderColor: theme.colors.primary,
  },
  modalChipText: {
    fontFamily: theme.typography.fontFamily.medium,
    fontSize: theme.typography.fontSizes.md,
    color: theme.colors.textSecondary,
  },
  modalChipTextSelected: {
    color: theme.colors.primary,
  },
  saveButton: {
    height: theme.dimensions.inputHeight,
    borderRadius: theme.radius.md,
    backgroundColor: theme.colors.primary,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.35,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 6,
  },
  saveButtonText: {
    fontFamily: theme.typography.fontFamily.semibold,
    fontSize: theme.typography.fontSizes["2xl"],
    fontWeight: theme.typography.fontWeights.semibold,
    color: theme.colors.textOnAccent,
  },
} as const);
